CREATE TABLE CUSTOMER (
ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(200),
LAST_NAME VARCHAR(200),
FULL_NAME VARCHAR(200),
GENDER VARCHAR(200),
CONTACT_NO VARCHAR(200),
ADDRESS VARCHAR(255),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP
);

CREATE TABLE ORDERS (
ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_NO VARCHAR(200),
CUSTOMER_ID INT,
STATUS VARCHAR(100),
ORDER_DATE TIMESTAMP,
AMOUNT DECIMAL(12,2),
IS_INVOICED TINYINT(1) DEFAULT 0,
IS_REFUNDED TINYINT(1) DEFAULT 0,
REFUND_AMOUNT DECIMAL(12,2) DEFAULT 0,
STATUS_CHANGE_DATE TIMESTAMP,
REMARKS VARCHAR(255),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP
);

CREATE TABLE ORDER_DETAIL (
ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
AMOUNT DECIMAL(12,2),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP
);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, FULL_NAME, GENDER, CONTACT_NO, ADDRESS, CREATED_BY)
VALUES ('Mr', 'General', 'Mr General', 'MALE', '1234567890', '123 Main St, Anytown USA', 'admin');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, FULL_NAME, GENDER, CONTACT_NO, ADDRESS, CREATED_BY)
VALUES ('Ms', 'General', 'Ms General', 'FEMALE', '9876543210', '456 Maple St, Anytown USA', 'admin');
