CREATE TABLE ACCOUNTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  ACTIVE TINYINT(1) DEFAULT 1,
  CREATED_BY VARCHAR(100),
  CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(100),
  UPDATED_AT TIMESTAMP,
  terminal VARCHAR(200)
);

CREATE TABLE GENERAL_LEDGER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID INT NOT NULL,
  INVOICE_ID INT NOT NULL,
  TRANSACTION_DATE TIMESTAMP,
  TRANSACTION_TYPE VARCHAR(100) NOT NULL,
  LEDGER_TYPE VARCHAR(100) NOT NULL,
  AMOUNT DECIMAL(10, 2) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(100),
  CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(100),
  UPDATED_AT TIMESTAMP,
  terminal VARCHAR(200)
);

INSERT INTO ACCOUNTS (NAME, DESCRIPTION, CREATED_BY)
VALUES
  ('CASH', 'Cash account', 'admin'),
  ('BANK', 'Bank account', 'admin');