CREATE TABLE INVOICE (
ID INT AUTO_INCREMENT PRIMARY KEY,
INVOICE_NO VARCHAR(200),
CUSTOMER_ID INT,
ORDER_ID INT,
STATUS VARCHAR(100),
INVOICE_DATE TIMESTAMP,
AMOUNT DECIMAL(12,2),
TAX_PERCENTAGE DECIMAL(12,2),
GST DECIMAL(12,2),
DISCOUNT_AMOUNT DECIMAL(12,2),
DISCOUNT_PERCENTAGE DECIMAL(12,2),
TOTAL_DISCOUNT DECIMAL(12,2),
TOTAL_AMOUNT DECIMAL(12,2),
CASH_RECEIVED DECIMAL(12,2),
BALANCE_AMOUNT DECIMAL(12,2),
IS_REFUNDED TINYINT(1) DEFAULT 0,
REFUND_AMOUNT DECIMAL(12,2) DEFAULT 0,
STATUS_CHANGE_DATE TIMESTAMP,
REMARKS VARCHAR(255),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP
);

CREATE TABLE INVOICE_DETAIL (
ID INT AUTO_INCREMENT PRIMARY KEY,
INVOICE_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
AMOUNT DECIMAL(12,2),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP
);