CREATE TABLE LOCATION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(200),
  DESCRIPTION VARCHAR(200),
  ADDRESS VARCHAR(200),
  ORGANIZATION_ID INT DEFAULT 1,
  MANAGER_NO VARCHAR(100),
  MANAGER_NAME VARCHAR(100),
  OPEN_TIME VARCHAR(100),
  CLOSE_TIME VARCHAR(100),
  CREATED_BY VARCHAR(100),
  CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(100),
  UPDATED_AT TIMESTAMP
);

CREATE TABLE TERMINAL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  COMPUTER_NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(255),
  IP_ADDRESS VARCHAR(255),
  MAC_ADDRESS VARCHAR(255),
  LOCATION_ID INT DEFAULT 1,
  EXPIRY_DATE TIMESTAMP,
  CREATED_BY VARCHAR(100),
  CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(100),
  UPDATED_AT TIMESTAMP
);

INSERT INTO LOCATION (ID, NAME, DESCRIPTION, ADDRESS, MANAGER_NO, MANAGER_NAME, OPEN_TIME, CLOSE_TIME, CREATED_BY, UPDATED_BY)
VALUES (1, 'MEMORIAL SMOKE', 'Description of Memorial Smoke', '123 Main St, Anytown USA', '123-456-7890', 'John Doe', '10:00 AM', '9:00 PM', 'Admin', 'Admin');

INSERT INTO TERMINAL (COMPUTER_NAME, DESCRIPTION, IP_ADDRESS, MAC_ADDRESS, LOCATION_ID, EXPIRY_DATE, CREATED_BY)
VALUES ('Java Development PC', 'This is my development computer', '127.0.0.1', '1c:91:80:da:40:0e', 1, '2030-05-12 00:00:00', 'admin');
