CREATE TABLE REFUND_ORDER (
ID INT AUTO_INCREMENT PRIMARY KEY,
REFUND_ORDER_NO VARCHAR(200),
ORDER_ID INT,
CUSTOMER_ID INT,
STATUS VARCHAR(100),
ORDER_DATE TIMESTAMP,
AMOUNT DECIMAL(12,2),
IS_INVOICED TINYINT(1) DEFAULT 0,
REFUND_AMOUNT DECIMAL(12,2) DEFAULT 0,
REMARKS VARCHAR(255),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP,
terminal_id INT
);

CREATE TABLE REFUND_ORDER_DETAIL (
ID INT AUTO_INCREMENT PRIMARY KEY,
REFUND_ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
AMOUNT DECIMAL(12,2),
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(100),
UPDATED_AT TIMESTAMP,
terminal_id INT
);