CREATE TABLE DATABASE_BACKUP (
ID INT AUTO_INCREMENT PRIMARY KEY,
BACKUP_DATE TIMESTAMP,
BACKUP_FILENAME varchar(255),
UPLOAD_STATUS varchar(255),
SHARING_STATUS varchar(255),
SCRIPT_STATUS varchar(255),
CLIENT_NAME varchar(255),
GOOGLE_DRIVE_FILE_ID varchar(255),
BACKUP_RESPONSE text,
CREATED_BY VARCHAR(100),
CREATED_AT TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP
);